language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y  # gcc-4.8
  - sudo add-apt-repository ppa:boost-latest/ppa -y         # boost-1.55.0
  - sudo add-apt-repository ppa:h-rayflood/llvm -y          # clang-3.5
  - sudo apt-get update -qq
  - sudo apt-get install -y libnetcdf-dev
  - sudo apt-get install -y g++-4.8        # Needed by clang for a C++11 stdlib
  - sudo apt-get install -y gfortran-4.8
  - export FC=gfortran-4.8
  - sudo apt-get install -y libboost1.55-dev
  - sudo apt-get install -y libboost-filesystem1.55.0 libboost-filesystem1.55-dev
  - sudo apt-get install -y libboost-python1.55-dev libboost-python1.55.0
  - sudo apt-get install -y python-numpy
  - |
    if [ ${CC} == "gcc" ]
    then
        export CC=gcc-4.8
        export CXX=g++-4.8
    fi
  - |
    if [ ${CC} == "clang" ]
    then
        sudo apt-get install -y clang-3.4
        export CC=clang-3.4
        export CXX=clang++-3.4
    fi

script: ./scripts/travis-build.sh
