language: cpp
sudo: false
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  global:
    secure: Mf7f3PP+AHqyOMEp9koj+mTBSVfo03XNFLJ6offmH3IWIj+N5fxwn+tN3H/hKUeL8mvzfHjXPAkYkWKVwcamoQ9ktoYLDJ83HCa4muCUxENz/SAR2DvWf8ix7ggvIP8wZCrNyq8ssw+5F1FRmauF7HjTDPCtBiz/sjvK94XVwXU=
    secure: vemv2pi+y10L/3QkiDTdgbsug2Qv97OUiMjyRw9pYIjDoNhws1jzuKMFJt1YvUNZcROUA1hEkDYDDCmGTXAo7zr+pk+ru9e8h6q9LH+uPZWKgWHUzEyFlLB3wve3fCzeTIqvvSC+87bxYhJg53TrrCyRXBu3jnHoqJKr2RhWwOQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    - kalakris-cmake
    packages:
    - g++-4.9
    - libnetcdf-dev
    - clang-3.6
    - cmake

before_install:
  # Setting environement
  - export C_COMPILER="$CC"
  - export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=debug -DBUILD_TESTS=ON -DENABLE_NETCDF=ON -DBUILD_SHARED_LIBS=ON"
  - |
    if test "$TRAVIS_OS_NAME" == "linux" && test "$C_COMPILER" == "gcc"; then
        export DO_COVERAGE=true
        export CMAKE_ARGS="$CMAKE_ARGS -DCODE_COVERAGE=ON"
        pip install --user codecov
    else
        export DO_COVERAGE=false
    fi
  # Install Linux stuff
  - |
    if test "${TRAVIS_OS_NAME}" == "linux"; then
        if [ ${C_COMPILER} == "gcc" ]
        then
            export CC=gcc-4.9
            export CXX=g++-4.9
        elif [ ${C_COMPILER} == "clang" ]
        then
            export CC=clang-3.6
            export CXX=clang++-3.6
        fi
    fi
  # Install OS X stuff
  - |
    if test "$TRAVIS_OS_NAME" == "osx"; then
        brew tap homebrew/science
        brew update
        brew rm gcc
        brew install gcc netcdf
        if [ ${C_COMPILER} == "gcc" ]
        then
            export CC=gcc-5
            export CXX=g++-5
        elif [ ${C_COMPILER} == "clang" ]
        then
            export CC=clang
            export CXX=clang++
        fi
    fi

install:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build
  - cd build
<<<<<<< HEAD
  - $CMAKE $CMAKE_ARGS ..
=======
  - cmake $CMAKE_ARGS ..
  # Cleanup of the coverage data
  - |
    if [ ${DO_COVERAGE} == 1 ]
    then
        ${LCOV} --directory $(pwd) --zerocounters
    fi
>>>>>>> Use Cmake 2.8.11 in Travis

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make
  - ctest --output-on-failure

after_success:
  - |
    if ${DO_COVERAGE}; then
        codecov --gcov-exec=gcov-4.9
    fi
