language: cpp

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y  # gcc-4.9
  - sudo add-apt-repository ppa:boost-latest/ppa -y         # boost-1.55.0
  - sudo add-apt-repository ppa:h-rayflood/llvm -y          # clang-3.5
  - sudo apt-get update -qq
  - sudo apt-get install -y libnetcdf-dev
  - sudo apt-get install -y g++-4.9        # Needed by clang for a C++11 stdlib
  - sudo apt-get install -y gfortran-4.9
  - export FC=gfortran-4.9
  - sudo apt-get install -y libboost1.55-dev
  - sudo apt-get install -y libboost-filesystem1.55.0 libboost-filesystem1.55-dev
  - sudo apt-get install -y libboost-python1.55-dev libboost-python1.55.0
  - sudo apt-get install -y python-numpy
  - sudo apt-get install -y lcov
  - |
    if [ ${CC} == "gcc" ]
    then
        export CC=gcc-4.9
        export CXX=g++-4.9
    fi
  - |
    if [ ${CC} == "clang" ]
    then
        sudo apt-get install -y clang-3.4
        export CC=clang-3.4
        export CXX=clang++-3.4
    fi
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sh cmake-3.2.1-Linux-x86_64.sh --prefix=. --exclude-subdir

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - ../bin/cmake -DCMAKE_BUILD_TYPE=debug -DCODE_COVERAGE=ON -DBUILD_TESTS=ON -DPYTHON_BINDING=ON -DFORTRAN_BINDING=ON ..
  # Cleanup the coverage data
  - lcov --directory . --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make
  - ctest --output-on-failure

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
