language: cpp
sudo: false
# Build matrix
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - BUILD_TYPE=debug SHARED_LIBS=ON
  - BUILD_TYPE=debug SHARED_LIBS=OFF
  - BUILD_TYPE=release SHARED_LIBS=ON
  - BUILD_TYPE=release SHARED_LIBS=OFF
matrix:
  fast_finish: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - g++-4.8
    - libnetcdf-dev
    - cmake

before_install:
  # Setting environement
  - export C_COMPILER="$CC"
  - export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_TESTS=ON -DENABLE_NETCDF=ON -DBUILD_SHARED_LIBS=${SHARED_LIBS}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" && "$BUILD_TYPE" == "debug" && "$SHARED_LIBS" == "ON" ]]; then
        export EXTRA_WORK=true
        export CMAKE_ARGS="$CMAKE_ARGS -DCODE_COVERAGE=ON"
        pip install --user codecov
    else
        export EXTRA_WORK=false
    fi
  # Install Linux stuff
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
        if test "${CC}" == "gcc"; then
            export CC=gcc-4.8
            export CXX=g++-4.8
        fi
    fi
  # Install OS X stuff
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew tap homebrew/science
        brew update
        brew rm gcc
        brew install gcc netcdf
        if test "${CC}" == "gcc"; then
            export CC=gcc-6
            export CXX=g++-6
        fi
    fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build
  - cd build
  - cmake $CMAKE_ARGS ..
  - make
  - ctest --output-on-failure

after_success:
  - |
    if ${EXTRA_WORK}; then
        codecov --gcov-exec=gcov-4.8
    fi
