language: cpp
sudo: false

linux64_addons:
    addons: &linux64
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - g++-4.8
        - cmake
        - doxygen
        - valgrind
        - libnetcdf-dev

linux32_addons:
    addons: &linux32
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - kalakris-cmake
        packages:
        - g++-4.8
        - cmake
        - doxygen
        - valgrind
        - g++-4.8-multilib
        - linux-libc-dev:i386
        - libc6-dev-i386

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: clang
      env: SHARED_LIBS=ON CMAKE_EXTRA=-DCHFL_SYSTEM_NETCDF=ON
      addons: *linux64
    - os: linux
      compiler: clang
      env: SHARED_LIBS=OFF
      addons: *linux64
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=ON
      addons: *linux64
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=OFF
      addons: *linux64
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=ON ARCH="x86" CMAKE_EXTRA=-DHAVE_LIBM=/lib32/libm.so.6
      addons: *linux32
    - os: linux
      compiler: gcc
      env: SHARED_LIBS=OFF ARCH="x86" CMAKE_EXTRA=-DHAVE_LIBM=/lib32/libm.so.6
      addons: *linux32
    - os: osx
      compiler: clang
      env: SHARED_LIBS=ON
    - os: osx
      compiler: clang
      env: SHARED_LIBS=OFF
    - os: osx
      compiler: gcc
      env: SHARED_LIBS=ON
    - os: osx
      compiler: gcc
      env: SHARED_LIBS=OFF

before_install:
  # Setting environement
  - cd $TRAVIS_BUILD_DIR
  - source scripts/ci/setup-travis.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake $CMAKE_ARGS $CMAKE_EXTRA ..
  - make
  - ctest --output-on-failure
  - |
    if ${EXTRA_WORK}; then
        cd $TRAVIS_BUILD_DIR
        # Generate and upload coverage
        codecov --gcov-exec=gcov-4.8
        # Check and generate documentation
        ./scripts/ci/check-capi.py
        git clone https://${GH_TOKEN}@github.com/chemfiles/chemfiles gh-pages
        ./scripts/ci/deploy-docs.sh
    fi

env:
  global:
    secure: "DituZnehFQWFs6o3h9+sqGDxlHIPTImWxBvzHjV0w7dmvKcl6rakf6fNsTjcM9lrk2Q9owxwzT7EWxhI/1E28ivtNwxWod6jMuwmrw+6jz7dQG0JTs3icTeCO6z1dnRaLRDHlVpiVob9Cz6ZYPCB86XzOeVlvh7693WXoHpZ944="
