language: cpp

compiler:
  - gcc
  - clang

install:
  - |

    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    sudo add-apt-repository ppa:boost-latest/ppa -y
    sudo apt-get update -qq
    sudo apt-get install -y libnetcdf-dev
    sudo apt-get install -y libboost1.55-dev libboost-filesystem1.55.0 libboost-filesystem1.55-dev
    if [ ${CC} == "gcc" ]
    then
        sudo apt-get install -y g++-4.8
        export CC=gcc-4.8
        export CXX=g++-4.8
    fi

script: ./scripts/travis-build.sh
