language: cpp

env:
  global:
    secure: Mf7f3PP+AHqyOMEp9koj+mTBSVfo03XNFLJ6offmH3IWIj+N5fxwn+tN3H/hKUeL8mvzfHjXPAkYkWKVwcamoQ9ktoYLDJ83HCa4muCUxENz/SAR2DvWf8ix7ggvIP8wZCrNyq8ssw+5F1FRmauF7HjTDPCtBiz/sjvK94XVwXU=

compiler:
  - gcc
  - clang

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y  # gcc-4.9
  - sudo add-apt-repository ppa:boost-latest/ppa -y         # boost-1.55.0
  - sudo add-apt-repository ppa:h-rayflood/llvm -y          # clang-3.5
  - sudo apt-get update -qq
  # Compilers
  - sudo apt-get install -y g++-4.9        # Needed by clang for a C++11 stdlib
  - sudo apt-get install -y gfortran-4.9
  # Libraries
  - sudo apt-get install -y libnetcdf-dev
  - sudo apt-get install -y libboost1.55-dev
  - sudo apt-get install -y libboost-filesystem1.55.0 libboost-filesystem1.55-dev
  - sudo apt-get install -y libboost-python1.55-dev libboost-python1.55.0
  - sudo apt-get install -y python-numpy
  # Coverage stuff
  - gem install coveralls-lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  # Setting environement
  - export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=debug -DBUILD_TESTS=ON -DPYTHON_BINDING=ON -DFORTRAN_BINDING=ON -DBUILD_FRONTEND=OFF"
  - export FC=gfortran-4.9
  - |
    if [ ${CC} == "gcc" ]
    then
        export CC=gcc-4.9
        export CXX=g++-4.9
        export CMAKE_ARGS="$CMAKE_ARGS -DCODE_COVERAGE=ON"
    fi
  - |
    if [ ${CC} == "clang" ]
    then
        sudo apt-get install -y clang-3.4
        export CC=clang-3.4
        export CXX=clang++-3.4
    fi
  - mkdir build
  - cd build
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sh cmake-3.2.1-Linux-x86_64.sh --prefix=. --exclude-subdir

before_script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - ./bin/cmake $CMAKE_ARGS ..
  # Cleanup the coverage data
  - lcov --directory $(pwd) --zerocounters

script:
  - cd ${TRAVIS_BUILD_DIR}/build
  - make
  - ctest --output-on-failure

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  # Parse and submit coverage data
  - lcov --gcov-tool gcov-4.9 --directory $(pwd) --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' 'Chemharp/build/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token=${COVERALLS_TOKEN} coverage.info
