version: "{build}"

os:
  - Visual Studio 2015

environment:
  matrix:
  - GENERATOR: Visual Studio 14 2015        # use mscv compiler in 32-bit mode
  - GENERATOR: Visual Studio 14 2015 Win64  # use mscv compiler in 64-bit mode

clone_depth: 10
clone_folder: c:\Chemharp

build:
  verbosity: minimal

notifications:
  - provider: Email
    to: [luthaf@luthaf.fr]
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - git submodule update --init

build_script:
  - cd C:\Chemharp
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=ON -G "%GENERATOR%" ..
  - cmake --build . --config debug --target ALL_BUILD

test_script:
  - ctest --build-config debug --output-on-failure -E dcd-molfile
