version: "{build}"

os: Visual Studio 2015

environment:
  matrix:
    - generator: Visual Studio 14 2015 Win64
      ARCH: x64
    - generator: Visual Studio 14 2015
      ARCH: x86
    - generator: MinGW Makefiles
      CXX_PATH: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'
      ARCH: x86

configuration:
  - Debug
  - Release

clone_depth: 10
clone_folder: c:\Chemharp

notifications:
  - provider: Email
    to: [luthaf@luthaf.fr]
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  - ps: . .\scripts\ci\setup-appveyor.ps1

build_script:
  - cd C:\Chemharp
  - mkdir build
  - cd build
  - ps: echo $env:CMAKE_ARGUMENTS
  - cmake %CMAKE_ARGUMENTS% ..
  - cmake --build . --config "%configuration%" -- %BUILD_ARGUMENTS%

test_script:
  - ctest --build-config "%configuration%" --timeout 300 --output-on-failure -E dcd-molfile
