version: "{build}"

environment:
  matrix:
    - generator: "Visual Studio 14 2015"
    - generator: "Visual Studio 14 2015 Win64"
    - generator: "MinGW Makefiles"
      CXX_PATH: 'C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin'

configuration:
  - Debug
  - Release

build:
    verbosity: quiet

clone_depth: 10
clone_folder: c:\Chemharp

notifications:
  - provider: Email
    to: [luthaf@luthaf.fr]
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true

install:
  # git bash conflicts with MinGW makefiles
  - if "%generator%"=="MinGW Makefiles" (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
  - if not "%CXX_PATH%"=="" (set "PATH=%PATH%;%CXX_PATH%")
  - set CMAKE_ARGUMENTS="-DCHFL_BUILD_TESTS=ON -G %generator% -DCMAKE_BUILD_TYPE=%configuration%"
  - ps: |
        if ($env:generator -eq "Visual Studio 14 2015") {
            C:\Miniconda35\Scripts\conda install --quiet --yes libnetcdf
            $env:CMAKE_ARGUMENTS += " -DCHFL_ENABLE_NETCDF=ON"
            $env:CMAKE_ARGUMENTS += " -DNETCDF_INCLUDES=C:\Miniconda35\Library\include"
            $env:PATH += ";C:\Miniconda35\Library\bin"
        } elseif ($env:generator -eq "Visual Studio 14 2015 Win64") {
            C:\Miniconda35-x64\Scripts\conda install --quiet --yes libnetcdf
            $env:CMAKE_ARGUMENTS += " -DCHFL_ENABLE_NETCDF=ON"
            $env:CMAKE_ARGUMENTS += " -DNETCDF_INCLUDES=C:\Miniconda35-x64\Library\include"
            $env:CMAKE_ARGUMENTS += " -DNETCDF_LIBRARIES=C:\Miniconda35-x64\Library\lib\netcdf.lib"
            $env:PATH += ";C:\Miniconda35-x64\Library\bin"
        }

build_script:
  - cd C:\Chemharp
  - mkdir build
  - cd build
  - cmake %CMAKE_ARGUMENTS% ..
  - cmake --build . --config "%configuration%"

test_script:
  - ctest --build-config "%configuration%" --timeout 300 --output-on-failure -E dcd-molfile
